## COPYRIGHT (C) HARRY CLARK 2026
## MOTOROLA 68000 STANDALONE EMULATION LIBRARY

## THIS FILE PERTAINS TOWARDS THE RULES ENCOMPASSING THE
## COMPILER OPTIMISATIONS FOR THE HOOK TRACE DEFINES

HOOKS_FLAG_NAMES		:= 		S X Z V C N
HOOKS_ALL_FLAGS			:=		$(foreach FLAG, $(HOOKS_FLAG_NAMES), -DM68K_$(FLAG)_FLAG_HOOK=1)

HOOKS_CCR				:=		-DM68K_CCR_LOGGING=1		$(HOOKS_ALL_FLAGS)
HOOKS_MEM				:=		-DMEM_MAP_TRACE_HOOK=1		-DMEM_TRACE_HOOK=1
HOOKS_ALL				:=		$(HOOKS_CCR) $(HOOKS_MEM)

HOOKS_TRACE_FLAGS		:=

## DIFFERENTIATE BETWEEN WHICH TRACE HOOK IS CURRENTLY BEING USED

ifdef TRACE
	ifeq ($(TRACE),ON)
        TRACE_FLAGS := $(HOOKS_ALL)
	else ifeq ($(TRACE),ALL)
        TRACE_FLAGS := $(HOOKS_ALL)
	else ifeq ($(TRACE),MEM)
        TRACE_FLAGS := $(HOOKS_MEM)
    else ifeq ($(TRACE),CCR)
		TRACE_FLAGS := $(HOOKS_CCR)
	endif
endif

